AllCops:
  Exclude:
  - 'bin/*'
  - 'db/*.rb'
  - 'vendor/**/*'
  - 'config/**/*'
  - 'test/**/*'
  - 'Guardfile'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'


Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 125

Metrics/ClassLength:
  Max: 130

Metrics/AbcSize:
  Max: 30

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
    Enabled: false

Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

