# Options here can still be overridden by cmd line args.
# sidekiq -C sidekiq.yml
---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [mailer, 2]